### PR TITLE
add: prop rotate

### PR DESCRIPTION
**Pull request by wenzhaoxu**
fix: add 'cross-env' & 'rollup' to package.json

### CODE REVIEW

**Comment by Justineo** [comment]
I'd rather do this using CSS because this feature disables setting `transform` from CSS after `rotate` prop is set.

**Comment by wenzhaoxu** [comment]
It's useful when  build a toolbar. 
I'm using vue-awsome in toolbar component. I define the toolbar item in an array, and used 'v-for' to display the item.
Example:
`let buttons = [{ title: 'arrow', icon: 'arrow', rotate: -45}, {title: 'font', icon:'font', rotate: 0];

<button v-for="button in buttons">
<icon :name="button.icon :rotate=button.rotate></icon>
</button>`

**Comment by wenzhaoxu** [comment]
```
let buttons = [{ title: 'arrow', icon: 'arrow', rotate: -45}, {title: 'font', icon:'font', rotate: 0];

<button v-for="button in buttons">
<icon :name="button.icon :rotate=button.rotate></icon>
</button>
```

**Comment by Justineo** [comment]
Actually I'm thinking that predefining `transform` styles is a bad idea because it prevents multiple `transform` styles to co-exist. eg. An icon cannot be both `flip="horizontal"` and `spin`. Let users to customize this using CSS seems a better way.

**Comment by wenzhaoxu** [comment]
Ok, I will republish a new project to provide the props.

**Pull request closed without merging**
