### PR TITLE
Update icons

### PR DESCRIPTION
**Pull request by Kelin2025**
Hello! Nice package, probably best solution I've seen  
I added icons from newest font-awesome.  
Got it from `advanced-options/raw-svg` folder here: https://use.fontawesome.com/releases/v5.0.8/fontawesome-free-5.0.8.zip  
I used your `publish.sh` script to build 
> **Note:** I didn't add icons from _solid_ folder because of similar naming

### CODE REVIEW

**Comment by Justineo** [comment]
The current build script will load `font-awesome@4.7.0` from npm and convert icon fonts into raw SVG files into `assets/svg`. Manually copy-pasted SVG icons might be overwritten by generated one I'm afraid and are hard to update. It seemed that icon fonts are still being published to npm after v5, the only difference is the location of the icon font folder has been changed and are separated into several icon sets.

I'm thinking about this:

1. Update [`fa2svg`](https://www.npmjs.com/package/fa2svg) (which is a forked version of [`font-awesome-svg`](https://www.npmjs.com/package/font-awesome-svg)) and load from `@fortawesome/fontawesome-free-webfonts/webfonts/fa-regular-400.svg` instead of `font-awesome/fonts/fontawesome-webfont.svg` and we can continue to use the current build script.

2. Put `brands`/`solid` icons into a deeper directory so we can have all free icons. Use them like:

    ```html
    <icon name="brands/500px"/>
    ```

**Comment by Kelin2025** [comment]
Ok, I was lazy yesterday ~_~  
I'll do it a little later

**Comment by SergejsZerins** [comment]
@Kelin2025 when are you planning to finish this ? Probably a lot of people waiting new great set of icons :)

**Comment by Kelin2025** [comment]
@SergejsZerins hello again! Sunday is OK?

**Comment by SergejsZerins** [comment]
@Kelin2025 hey, are you going to make a new commit ? Sorry for disturbing you :)

**Comment by Kelin2025** [comment]
save  
me

image

---

I'm working on big refactoring of my work project, sorry for false promise. When I'll have a time, I'll finish it

**Comment by Justineo** [comment]
@Kelin2025 Don't feel obliged to do this. Actually the solution I mentioned earlier requires some modification on `fa2svg` and I haven't got time to work on that yet. And I'll be available to do this after this weekend. You work projects always have the highest priority so don't worry 😄

**Comment by Justineo** [comment]
@Kelin2025 I made quite a lot updates on the build script and dependent toolchain before update to FA5 and it's not easy to integrate this PR into it so I'm gonna close this. But still thank you very much in contributing your time here. I just published `vue-awesome@3.0.0` with all free icons in FA5 and I hope folks will like it. 😃

**Pull request closed without merging**
